# Generated by Django 4.0.5 on 2022-06-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurnattable',
            name='weekday',
            field=models.CharField(choices=[('MON', '월요일'), ('TUE', '화요일'), ('WED', '수요일'), ('THU', '목요일'), ('FRI', '금요일'), ('SAT', '토요일'), ('SUN', '일요일')], default='MON', max_length=3),
        ),
    ]

