# Generated by Django 4.0.5 on 2022-06-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_restauranttable_weekday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurnatTable',
            new_name='RestaurantTable',
        ),
    ]
